Algoritmo "semnome"

Var
// Seção de Declarações das variáveis 
  numeroA: inteiro
  numeroB: inteiro
  resultado: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   //este codigo faz uma soma
   escreval ( "Informe um número Inteiro:")
   leia(numeroA)
   escreval ("Informe outro número Inteiro:")
   leia (numeroB)
   resultado <- numeroA + numeroB
   escreval ("O resultado é:", resultado, "!")
Fimalgoritmo