Algoritmo "semnome"
Var
// Seção de Declarações das variáveis 
  cambioDolar: real
  valorReal: real
  conversao: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreval ("Digite o valor do câmbio do dólar:")
  leia (cambioDolar)
  escreval ("Digite o valor do dólar:")
  leia (conversao)
  valorReal <- conversao/cambioDolar
  escreval ("Essa conversão é igual a", valorReal, "reais!")

Fimalgoritmo