Algoritmo "Troca de valores"
Var
   A, B, C: real
Inicio
      escreval("Digite um valor para a varivel A:")
      leia(A)
      escreval("Digite um valor para a variavel B")
      leia(B)
      escreval("A Variavel A armazena",A," e a variavel B armazena",B)
      C <- A
      A <- B
      B <- C
      escreval("A variavel A agora recebeu o valor",A," e a variavel B recebeu o valor",B)
Fimalgoritmo