Algoritmo "exercicio_02"
//Faça um pseudocódigo que solicite um número
//e diga se ele é: Par ou ímpar

Var
   // Seção de Declarações das variáveis
   valor : real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite um numero, para ver se é par ou impar: ")
   leia(valor)

   se(valor%2 = 0)entao
      escreval("seu numero é par")

   senao
      escreval("seu numero é impar")

   fimse
Fimalgoritmo