Algoritmo "Exercicio01"
//Faça um pseudocódigo que solicite um número e
// diga se ele é: Positivo ou Negativo.

Var
   // Seção de Declarações das variáveis
   valor : real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite um numero, para ver se é positivo ou negativo: ")
   leia(valor)

   se(valor>0)entao
      escreval("seu numero é positivo")

   senao
      escreval("seu numero é negativo")

   fimse
Fimalgoritmo