Algoritmo "dois"

Var
   numeroA: inteiro
   antecessor: inteiro
   sucessor: inteiro

Inicio
      escreval("Informe um número inteiro")
      leia(numeroA)
      antecessor <- numeroA-1
      sucessor <- numeroA+1
      escreva("O número informado foi", numeroA)
      escreva(" o antecessor é", antecessor)
      escreva(" e o sucessor é", sucessor)
      
      


Fimalgoritmo
