Algoritmo "questao4"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/09/2023
Var
   // Seção de Declarações das variáveis
   i:  inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval ("---Exibindo números de 0 a 100 com um intervalo de 5 números---")
   para i de 0 ate 100 passo 5 faça
      escreval (i)
   fimpara

Fimalgoritmo