Algoritmo "questao7"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/09/2023
Var
   // Seção de Declarações das variáveis
   i: inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval ("---Verificando dobros de 10 a 100---")
   para i de 10 até 100 faça
      escreval(i," x 2 =",i*2)
   fimpara

Fimalgoritmo