Algoritmo "Questão3"

Var
   janeiro: real
   fevereiro: real
   marco: real
   media: real
Inicio
      escreval("Informe os lucros de janeiro")
      leia(janeiro)
      escreval("Informe os lucros de fevereiro")
      leia(fevereiro)
      escreval("Informe os lucros de março")
      leia(marco)
      escreva("A média de lucro é ")
      media <- (janeiro + fevereiro + marco) / 3
      escreva(media)
Fimalgoritmo