Algoritmo "ATIVIDADE 2 - QUESTÃO 2"
// Disciplina   : Algoritmos
// Professora   : Marisangela Alves 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Brunno Pedro de Oliveira
// Data atual  : 05/09/2023
Var
   numero: real


Inicio
      escreval("Digite um número: ")
      leia(numero)
      
      SE (numero % 2 = 0) ENTAO
         escreval("O número é par. ")
      SENAO
           escreval("O número é ímpar. ")
      FIMSE


Fimalgoritmo