Algoritmo "semnome"

Var
   numero: real
Inicio
   escreval ("---Verificando número numeros positivos ou negativos---")
   escreva ("Digite um número: ")
   leia (numero)
   se numero = 0 entao
      escreval ("O número que você digitou é nulo!")
   fimse
   se numero > 0 então
      escreva ("O número escolhido é positivo!")
   senão
      escreva ("O número que você escolheu é negativo!")
   fimse

Fimalgoritmo