Algoritmo "Questão2"

Var
   numeroInteiro: inteiro
   sucessorInteiro: inteiro
   antecessorInteiro: inteiro
Inicio
      escreval("Digite um número inteiro.")
      leia(numeroInteiro)
      sucessorInteiro <- numeroInteiro + 1
      antecessorInteiro <- numeroInteiro - 1
      escreva("O número escolhido " , numeroInteiro, " possui ")
      escreva("antecessor " , antecessorInteiro)
      escreva(" e sucessor " , sucessorInteiro)
Fimalgoritmo