Algoritmo "semnome"

Var
   lucroJaneiro: real
   lucroFevereiro: real
   lucroMarco:real
   media: real
Inicio
      escreval("Qual o lucro do mes de Janeiro? ")
      leia(lucroJaneiro)
      escreval("Qual o lucro do mes de Fevereiro? ")
      leia(lucroFevereiro)
      escreval("Qual o lucro do mes de Março? ")
      leia(lucroMarco)
      media <-  (lucroJaneiro + lucroFevereiro + lucroMarco) / 3
      escreval(media)


Fimalgoritmo