Algoritmo "Par_ou_Impar"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
   numero:real

Inicio
   escreval ("_____Algoritmo Par ou Ímpar_____")
   escreval
   escreva("Digite um número: ")
   leia(numero)
   
   SE numero mod 2 = 0 ENTAO
   escreva("Seu número é par!")
   
   SENAO
   escreva("Seu número é ímpar!")
   FIMSE
   
Fimalgoritmo
