Algoritmo "Questão 1"
Var
   codigo: inteiro

Inicio

   escreva("Digite um código: ")
   leia(codigo)

   escolha codigo

   caso 1254
      escreval("Sanduíche de presunto - R$8,00")

   caso 5698
      escreval("Churros - R$3,50")

   caso 7114
      escreval("Suco de laranja que parece de limão mas tem gosto de tamarindo - R$ 5,00")

   outrocaso
      escreval("Código Inválido")
   fimescolha



Fimalgoritmo