Algoritmo "questão7"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/09/2023
Var
salário: real
valorPrestacao: real
credito: real


Inicio

escreva ("Qual o valor do seu salário bruto? ")
leia (salario)
escreva ("Qual o valor da prestação?")
leia (valorPrestacao)
credito <- 0.3 * salario

SE
ENTAO
FIMSE



Fimalgoritmo