Algoritmo "semnome"

Var
// Seção de Declarações das variáveis 
numero: real
numero2: real
numero3: real
resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Lucro de Janeiro")
leia(numero)
escreval("O de Fevereiro")
leia(numero2)
escreval("E o de Março")
leia(numero3)
resultado <- numero + numero2 + numero3 /3
escreval("Sua média é",resultado)
Fimalgoritmo