Algoritmo "questao5"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/08/2023
Var
   // Seção de Declarações das variáveis
   lado, area: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval ("Informe o tamanho de um lado do quadrado: ")
   leia (lado)
   area <- lado^2
   escreva ("A área total do quadrado é de: ", area)

Fimalgoritmo