Algoritmo "ATIVIDADE 8 - QUESTÃO 15"
// Disciplina   : Algoritmos
// Professora   : Marisangela Alves
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Brunno Pedro de Oliveira
// Data atual  : 18/09/2023
Var
   i, passe, numero: inteiro

Inicio
   numero <- 1
   passe <- 1

   para i de 1 ate 11 faca
      passe <- passe + 2
      numero <- numero + passe
      escreval(numero)
   fimpara

fimalgoritmo