Algoritmo "questao1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/09/2023
Var
x: inteiro


Inicio
   para x de 1 até 8 faça
   timer(100)
      escreval("Não deixe ninguém seu dia, destrua você mesmo!")
   fimpara


Fimalgoritmo