Algoritmo "questao6"
Var
   x: inteiro
   inputUser, incremento: inteiro



Inicio
   escreval("                   === ENTRADA E INCREMENTO ===")
   escreval
   escreval
   escreva("Digite um número inteiro: ")
   leia(inputUser)
   escreva("Digite um número inteiro para incremento: ")
   leia(incremento)

   para x de 0 até inputUser passo incremento faça
   escreval("Saída:",x)
   fimpara

Fimalgoritmo