Algoritmo "Questao 11"

Var
valorCompra, parcela, valorParcela: real


Inicio
   escreval ("Qual foi o valor total da sua compra?")
   leia(valorCompra)
   escreval("Em quantas vezes deseja parcelar sua compra?")
   leia (parcela)
   valorParcela<- valorCompra/parcela
   escreval ("Sua compra foi de ",(valorCompra)," reais você optou por parcelar em ",(parcela)," vezes. Sua parcela mensal é de ",(valorParcela), " reais.")


Fimalgoritmo