Algoritmo "semnome"

Var
   numero: inteiro
   numeroAntecessor: inteiro
   numeroSucessor: inteiro
Inicio
      escreval(" digite um numero inteiro para ver o seu antecessor e sucessor")
      leia(numero)
      numeroAntecessor <- numero - 1
      numeroSucessor <- numero + 1
      escreval ("O numero antecessor é ", numeroAntecessor)
      escreval ("O numero sucessor é ", numeroSucessor)
      
      

Fimalgoritmo