Algoritmo "Exercicio01"

Var
   matrizA: vetor [1..3,1..3] de inteiro
   i,j:inteiro
   
funcao menorNumero
inicio
   para i de 1 ate 3 faca
      escreval
      para j de 1 ate 3 faca
      escreval(frase)
   fimpara
fimprocedimento

Inicio
escreval("            ======== REPETICAO DE PALAVRAS ========")
escreval
escreval("Digite uma frase:")
leia(frase)
escreval("Digite a quantidade de vezes que irá repetir:")
leia(qtdRepeticao)

repetirMensagens()

Fimalgoritmo