algoritmo "Nome do Programa"
var
     sA: vetor[0..9] de inteiro
     i: inteiro
inicio
    para i de 1 ate 10 faca
        escreval(i,"Digite um número para uma sequência: ")
        leia (sA[i])
        escreval(sA[i])
   fimpara

   escreval("-----------------------------------------")

    para i de 10 ate 1 faca
        escreval (sA[i])
    fimpara
fimalgoritmo

//i <- 10
    //repita
        //escreval (sA[i])
         //i <- i - 1
    //ate i = 0